---
stages:
  - test
  - build
  - deploy

run-tests:
  stage: test
  image: bellsoft/liberica-openjdk-alpine-musl:11
  cache:
    key: "test"
    paths:
      - .gradle/
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew --quiet --no-daemon clean build jacocoTestReport
    - grep -oE 'Total[^\%]*?[0-9]{1,3}%' build/reports/jacoco/test/html/index.html
  artifacts:
    when: on_failure
    expire_in: 1 day
    paths:
      - build/reports/*
  except:
    - tags
  tags:
    - docker
